<?php
/**
 * R-TEL chat API
 * - Answers only system-related and product-finding questions
 * - Reads available products from DB (budget/brand matching)
 * - When GROQ_API_KEY or OPENAI_API_KEY is set, the main reply is generated by a real LLM
 */
ini_set('display_errors', '0');
error_reporting(E_ALL);
header("Content-Type: application/json; charset=utf-8");

if (!function_exists('rtel_chat_api_fail_json')) {
    function rtel_chat_api_fail_json($message = 'Assistant API error')
    {
        if (!headers_sent()) {
            header("Content-Type: application/json; charset=utf-8");
        }
        echo json_encode([
            'success' => false,
            'reply' => (string)$message,
            'products' => [],
        ]);
        exit();
    }
}

set_error_handler(function ($severity, $message, $file, $line) {
    // Convert runtime warnings/notices into a clean JSON response for frontend fetch().
    rtel_chat_api_fail_json('Assistant API runtime warning: ' . (string)$message);
});

set_exception_handler(function ($e) {
    rtel_chat_api_fail_json('Assistant API exception: ' . (string)$e->getMessage());
});

require_once __DIR__ . "/../connection.php";
require_once __DIR__ . "/chat_training_rules.php";
require_once __DIR__ . "/chat_ai_provider.php";
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

function respond($payload)
{
    echo json_encode($payload);
    exit();
}

function normalizeUserMessage($message)
{
    $msg = (string)$message;
    $msg = html_entity_decode($msg, ENT_QUOTES | ENT_HTML5, "UTF-8");
    $msg = preg_replace('/[^\p{L}\p{N}\s\-\.,\/\?]/u', ' ', $msg);
    $msg = preg_replace('/([!?.,])\1+/', '$1', $msg);
    $msg = preg_replace('/\s+/u', ' ', $msg);
    return trim((string)$msg);
}

function isLikelyMessyInput($message)
{
    $raw = trim((string)$message);
    if ($raw === "") return false;
    $len = mb_strlen($raw);
    if ($len < 4) return false;
    $letters = preg_match_all('/[\p{L}]/u', $raw);
    $nonWord = preg_match_all('/[^ \p{L}\p{N}]/u', $raw);
    $ratio = $len > 0 ? ($nonWord / $len) : 0;
    if ($ratio > 0.28) return true;
    if ($letters > 0 && $letters <= 2 && $len >= 6) return true;
    return false;
}

function guessIntentFromMessyInput($message)
{
    $m = mb_strtolower((string)$message);
    $productHints = ['phon', 'mob', 'sams', 'iph', 'redm', 'xia', 'vivo', 'oppo', 'noki', 'real', 'onep', 'price', 'budg', 'stok', 'spec', 'cam', 'bat', 'ram'];
    $supportHints = ['login', 'logn', 'pass', 'pwd', 'cart', 'chck', 'check', 'pay', 'err', 'bug', 'slow', 'load', 'order', 'ship', 'coupon'];
    foreach ($productHints as $h) {
        if (mb_strpos($m, $h) !== false) return 'product';
    }
    foreach ($supportHints as $h) {
        if (mb_strpos($m, $h) !== false) return 'support';
    }
    return 'unknown';
}

function simplifyEnglishReply($text)
{
    $t = trim((string)$text);
    if ($t === "") return $t;
    $map = [
        'utilize' => 'use',
        'approximately' => 'about',
        'purchase' => 'buy',
        'assistance' => 'help',
        'regarding' => 'about',
        'troubleshoot' => 'fix',
        'cannot' => 'can not',
        'do not' => "don't",
        'does not' => "doesn't",
    ];
    $out = str_ireplace(array_keys($map), array_values($map), $t);
    $out = preg_replace('/\s+/u', ' ', $out);
    return trim((string)$out);
}

function generateChatSessionId()
{
    return substr("S" . strtoupper(uniqid()), 0, 10);
}

function ensureChatSessionTable($conn)
{
    mysqli_query($conn, "CREATE TABLE IF NOT EXISTS tblchat_session (
        session_id VARCHAR(10) NOT NULL PRIMARY KEY,
        cus_id VARCHAR(250) NOT NULL,
        startTime TIME NOT NULL,
        endTime TIME NOT NULL,
        topic VARCHAR(100) NOT NULL,
        resolved TINYINT(1) NOT NULL DEFAULT 0,
        transcript TEXT NOT NULL
    )");
}

function createChatSession($conn, $userId, $topic)
{
    $sessionId = generateChatSessionId();
    $nowTime = date("H:i:s");
    $topicSafe = mb_substr(trim((string)$topic), 0, 100);
    if ($topicSafe === "") {
        $topicSafe = "General Support";
    }
    $emptyTranscript = json_encode([]);
    $stmt = $conn->prepare("INSERT INTO tblchat_session (session_id, cus_id, startTime, endTime, topic, resolved, transcript) VALUES (?, ?, ?, ?, ?, 0, ?)");
    if ($stmt) {
        $stmt->bind_param("ssssss", $sessionId, $userId, $nowTime, $nowTime, $topicSafe, $emptyTranscript);
        $stmt->execute();
        $stmt->close();
    }
    return $sessionId;
}

function appendToTranscript($conn, $sessionId, $userText, $assistantText)
{
    $currentTranscript = "[]";
    $currentTopic = "General Support";
    $select = $conn->prepare("SELECT transcript, topic FROM tblchat_session WHERE session_id = ? LIMIT 1");
    if ($select) {
        $select->bind_param("s", $sessionId);
        $select->execute();
        $row = $select->get_result()->fetch_assoc();
        if ($row) {
            $currentTranscript = (string)($row["transcript"] ?? "[]");
            $currentTopic = (string)($row["topic"] ?? "General Support");
        }
        $select->close();
    }
    $entries = json_decode($currentTranscript, true);
    if (!is_array($entries)) $entries = [];
    $timestamp = date("Y-m-d H:i:s");
    $entries[] = ["role" => "user", "text" => (string)$userText, "time" => $timestamp];
    $entries[] = ["role" => "assistant", "text" => (string)$assistantText, "time" => $timestamp];
    if (count($entries) > 200) $entries = array_slice($entries, -200);
    $encoded = json_encode($entries);
    $endTime = date("H:i:s");
    $update = $conn->prepare("UPDATE tblchat_session SET transcript = ?, endTime = ?, topic = ? WHERE session_id = ?");
    if ($update) {
        $update->bind_param("ssss", $encoded, $endTime, $currentTopic, $sessionId);
        $update->execute();
        $update->close();
    }
}

function getLatestChatHistory($conn, $userId)
{
    $stmt = $conn->prepare("SELECT session_id, transcript FROM tblchat_session WHERE cus_id = ? ORDER BY endTime DESC LIMIT 1");
    if (!$stmt) return ["session_id" => "", "messages" => []];
    $stmt->bind_param("s", $userId);
    $stmt->execute();
    $row = $stmt->get_result()->fetch_assoc();
    $stmt->close();
    if (!$row) return ["session_id" => "", "messages" => []];
    $messages = json_decode((string)($row["transcript"] ?? "[]"), true);
    if (!is_array($messages)) $messages = [];
    return ["session_id" => (string)$row["session_id"], "messages" => $messages];
}

function isClearHistoryCommand($message)
{
    $msg = strtolower(trim((string)$message));
    foreach (["erase history", "erase all history", "clear history", "clear all history"] as $command) {
        if ($msg === $command) return true;
    }
    return false;
}

function extractBudget($message)
{
    $msg = strtolower($message);
    $msg = str_replace([",", "/-"], "", $msg);
    if (preg_match('/(\d+)\s*k\b/', $msg, $m)) return (int)$m[1] * 1000;
    if (preg_match('/(?:under|below|less than|max(?:imum)?)\s*(\d{3,7})/', $msg, $m)) return (int)$m[1];
    if (preg_match('/budget\s*(?:of|is|=)?\s*(\d{3,7})/', $msg, $m)) return (int)$m[1];
    return null;
}

function isAllowedTopic($message, $keywords)
{
    $msg = strtolower($message);
    foreach ($keywords as $k) if (strpos($msg, strtolower($k)) !== false) return true;
    return false;
}

function isProductIntent($message)
{
    $msg = strtolower($message);
    $hints = ["phone","phones","mobile","tablet","watch","product","products","item","items","catalog","budget","under","below","price","cost","find","compare","versus","vs","warranty","spec","specs","feature","features","detail","details","about","model","modal","tell me","available","availability","stock","in stock","carry","sell","shop","buy","iphone","samsung","galaxy","redmi","xiaomi","pixel","vivo","oppo","nokia","realme","oneplus","accessory","accessories","charger","case","cover","earphone","headphone","cable"];
    foreach ($hints as $hint) if (strpos($msg, $hint) !== false) return true;
    return false;
}

function isSupportIssueIntent($message)
{
    $msg = strtolower($message);
    $hints = ["bug","bugs","error","errors","glitch","broken","crash","crashed","frozen","freeze","stuck","not working","doesn't work","does not work","dont work","don't work","won't work","will not work","won't load","will not load","not load","slow","timeout","timed out","failed","failure","cannot ","can't ","can not ","unable to","does nothing","nothing happens","blank page","issue","problem","troubleshoot","fix","404","500"];
    foreach ($hints as $hint) if (strpos($msg, $hint) !== false) return true;
    return false;
}

function detectBrandFromMessage($conn, $message)
{
    $msg = strtolower($message);
    $brandQuery = mysqli_query($conn, "SELECT brand_id, name FROM tblbrand WHERE status = 1");
    if (!$brandQuery) return null;
    while ($brand = mysqli_fetch_assoc($brandQuery)) {
        $brandName = strtolower((string)$brand["name"]);
        if ($brandName !== "" && strpos($msg, $brandName) !== false) {
            return ["brand_id" => (int)$brand["brand_id"], "brand_name" => (string)$brand["name"]];
        }
    }
    return null;
}

function resolveFaqAnswer($message, $faqRules)
{
    $msg = strtolower($message);
    foreach ($faqRules as $keyword => $answer) if (strpos($msg, strtolower($keyword)) !== false) return $answer;
    return null;
}

function stripProductDescriptionForChat($html)
{
    $t = strip_tags((string)$html);
    $t = html_entity_decode($t, ENT_QUOTES | ENT_HTML5, "UTF-8");
    $t = preg_replace("/\s+/u", " ", $t);
    return trim($t);
}

function normalizeFeatureBlobForChat($blob)
{
    $raw = trim((string)$blob);
    if ($raw === '') return '';
    $parts = preg_split('/\s*\|\s*/', $raw);
    $lines = [];
    foreach ((array)$parts as $part) {
        $part = trim((string)$part);
        if ($part === '') continue;
        $lines[] = preg_replace('/\s+/u', ' ', $part);
    }
    return implode("\n", array_slice($lines, 0, 20));
}

function extractProductSearchKeywords($message)
{
    $stop = ["the","a","an","is","are","was","were","what","when","where","which","who","how","why","tell","me","about","can","you","please","need","want","looking","for","with","this","that","these","those","from","web","site","system","buy","get","give","show","find","help","phone","phones","mobile","smartphone","product","products","budget","under","below","less","than","price","cost","rs","lkr","any","some","have","has","does","did","will","would","could","feature","features","spec","specs","specification","specifications","detail","details","information","available","availability","stock","listed","catalog","shop","store","order","cart","hey","hello","hi","thanks","thank","rtel","assistant","ai","in","on","at","to","of"];
    $msg = mb_strtolower($message);
    $msg = preg_replace("/[^\p{L}\p{N}\s]+/u", " ", $msg);
    $words = preg_split("/\s+/u", $msg, -1, PREG_SPLIT_NO_EMPTY);
    $out = [];
    foreach ($words as $w) {
        if (mb_strlen($w) < 2 || in_array($w, $stop, true)) continue;
        $out[] = $w;
    }
    return array_slice(array_values(array_unique($out)), 0, 8);
}

function keywordCoverageCount(array $row, array $keywords)
{
    if (count($keywords) === 0) return 0;
    $descPlain = mb_strtolower(stripProductDescriptionForChat($row["description"] ?? ""));
    $featHay = mb_strtolower(preg_replace('/\s+/u', ' ', (string)($row["feature_blob"] ?? "")));
    $hay = mb_strtolower(($row["name"] ?? "") . " " . ($row["modal"] ?? "") . " " . $descPlain . " " . $featHay);
    $n = 0;
    foreach ($keywords as $kw) {
        if ($kw !== "" && mb_strlen($kw) >= 2 && mb_strpos($hay, $kw) !== false) $n++;
    }
    return $n;
}

function scoreProductKeywordMatchRow(array $row, array $keywords)
{
    if (count($keywords) === 0) return 0;
    $descPlain = mb_strtolower(stripProductDescriptionForChat($row["description"] ?? ""));
    $featHay = mb_strtolower(preg_replace('/\s+/u', ' ', (string)($row["feature_blob"] ?? "")));
    $nameHay = mb_strtolower(($row["name"] ?? "") . " " . ($row["modal"] ?? ""));
    $hay = $nameHay . " " . $descPlain . " " . $featHay;
    $score = 0;
    foreach ($keywords as $kw) {
        if ($kw === "" || mb_strlen($kw) < 2) continue;
        if (mb_strpos($hay, $kw) === false) continue;
        $score++;
        if (mb_strpos($nameHay, $kw) !== false) {
            $score++;
        }
    }
    return $score;
}

function detectMultiProductBrowseIntent($message)
{
    $m = mb_strtolower((string)$message);
    if (preg_match('/\b(under|below|less than)\s*\d/', $m)) return true;
    if (preg_match('/\b(budget|cheap|cheapest|affordable)\b/', $m)) return true;
    if (preg_match('/\b(best|recommended?|tops?\s+\d+)\b/', $m)) return true;
    if (preg_match('/\b(?:compare|comparison|versus|vs\.?)\b/', $m)) return true;
    if (preg_match('/\b(show me|browse|everything|list\b)\b/', $m)) return true;
    if (preg_match('/\b(any|some)\s+(phone|phones|mobile|smartphone|product)/', $m)) return true;
    if (preg_match('/\b(phones?|products?)\s+(under|below)/', $m)) return true;
    if (preg_match('/\ball\s+(the\s+)?(phones|products|items)\b/', $m)) return true;
    return false;
}

/**
 * User is asking about a specific handset/item (narrow catalog to best match(es)).
 */
function detectSingleProductAskIntent($message)
{
    if (detectMultiProductBrowseIntent($message)) {
        return false;
    }
    $m = (string)$message;
    $patterns = [
        '/\btell\s+me\s+about\b/ui',
        '/\btell\s+about\b/ui',
        '/\btalk\s+about\b/ui',
        '/\bknow\s+about\b/ui',
        '/\bwhat\'s\b/ui',
        '/\bwhats\b/ui',
        '/\bwhat\s+is\b/ui',
        '/\bwhat\s+are\b/ui',
        '/\binformation\s+(?:about|on)\b/ui',
        '/\bdetails?\s+(?:about|on|for)\b/ui',
        '/\bdescribe(?:\s+the)?\b/ui',
        '/\b(?:do\s+you\s+have|have\s+you\s+got|did\s+you\s+have)\b/ui',
        '/\b(?:carry\s+the|carry\s+this|sell\s+the)\b/ui',
        '/\bavailability\s+(?:of|for)\b/ui',
        '/\bin\s+stock\b/ui',
        '/\bprice\s+(?:of|for)\b/ui',
        '/\bcost\s+of\b/ui',
        '/\bhow\s+much\b/ui',
        '/\b(?:specs?|specifications?)(?:\s+(?:of|for))?\b/ui',
        '/\babout\s+the\b/ui',
        '/\babout\s+this\b/ui',
        '/\bwhat\s+about\b/ui',
        '/\blooking\s+for\b/ui',
    ];
    foreach ($patterns as $p) {
        if (preg_match($p, $m)) {
            return true;
        }
    }
    return false;
}

/**
 * When the user asks about one product and R-TEL has a clear catalog match, return only that row so the AI and UI do not spam every similar item.
 *
 * @param array<int,array<string,mixed>> $rows
 * @return array<int,array<string,mixed>>
 */
function narrowChatProductRowsToBestMatch(array $rows, array $keywords, $message)
{
    if (count($rows) === 0) {
        return $rows;
    }
    if (count($keywords) === 0) {
        return array_slice($rows, 0, 8);
    }
    $multiBrowse = detectMultiProductBrowseIntent($message);
    if ($multiBrowse) {
        return array_slice($rows, 0, 8);
    }
    $c0 = keywordCoverageCount($rows[0], $keywords);
    $kwN = count($keywords);
    $c1 = count($rows) > 1 ? keywordCoverageCount($rows[1], $keywords) : -1;

    $pinOne = false;
    if (count($rows) === 1) {
        $pinOne = true;
    } elseif ($c0 === $kwN && $kwN >= 1 && $c0 > max(0, $c1)) {
        // Every search token appears on the top hit and not on runner-up coverage.
        $pinOne = true;
    } elseif (detectSingleProductAskIntent((string)$message)) {
        if ($c0 > 0 && $c1 === 0) {
            $pinOne = true;
        } elseif ($c0 - $c1 >= 2) {
            $pinOne = true;
        }
    }

    if ($pinOne) {
        return [$rows[0]];
    }
    return array_slice($rows, 0, 8);
}

function fetchProductsForChat($conn, $message, $budget, $brandMatch)
{
    $keywords = extractProductSearchKeywords($message);
    $msgLower = mb_strtolower((string)$message);
    $wantsPhonesOnly = (bool)preg_match('/\b(phone|phones|mobile|smartphone)\b/u', $msgLower);
    $phoneCategoryFilterSql = "LOWER(TRIM(COALESCE(c.name, ''))) IN ('smart phones','phones','budget phones','flagship phones')";
    $sql = "SELECT p.product_id, p.name, p.modal, p.description, p.price, p.cprice, p.quantity,
                   COALESCE(f.feature_blob, '') AS feature_blob,
                   COALESCE(b.name, '') AS brand_name, i.image_1
            FROM tblproduct p
            LEFT JOIN tblbrand b ON p.brand_id = b.brand_id AND b.status = 1
            LEFT JOIN tblcategory c ON p.cat_id = c.cat_id
            LEFT JOIN (
                SELECT product_id, GROUP_CONCAT(CONCAT(feature_name, ': ', feature_value) ORDER BY feature_id SEPARATOR ' | ') AS feature_blob
                FROM tblproduct_feature
                GROUP BY product_id
            ) f ON f.product_id = p.product_id
            LEFT JOIN tblimage i ON p.product_id = i.product_id
            WHERE p.status = 1 AND p.quantity > 0";
    $types = "";
    $params = [];
    if ($budget !== null && $budget > 0) { $sql .= " AND p.price <= ?"; $types .= "d"; $params[] = (float)$budget; }
    if ($brandMatch) { $sql .= " AND p.brand_id = ?"; $types .= "i"; $params[] = (int)$brandMatch["brand_id"]; }
    if ($wantsPhonesOnly) $sql .= " AND (" . $phoneCategoryFilterSql . ")";
    if (count($keywords) > 0) {
        $ors = [];
        foreach ($keywords as $kw) {
            $like = "%" . $kw . "%";
            $ors[] = "(LOWER(p.name) LIKE ? OR LOWER(COALESCE(p.modal, '')) LIKE ? OR LOWER(COALESCE(p.description, '')) LIKE ?)";
            $types .= "sss";
            $params[] = $like; $params[] = $like; $params[] = $like;
        }
        $sql .= " AND (" . implode(" OR ", $ors) . ")";
    }
    $sql .= " ORDER BY p.price ASC LIMIT 48";
    $stmt = $conn->prepare($sql);
    if (!$stmt) return [[], $keywords];
    if ($types !== "") {
        $bind = [$types];
        foreach ($params as $k => $v) $bind[] = &$params[$k];
        call_user_func_array([$stmt, "bind_param"], $bind);
    }
    $stmt->execute();
    $res = $stmt->get_result();
    $rows = [];
    while ($res && $row = $res->fetch_assoc()) $rows[] = $row;
    $stmt->close();
    // If noisy keywords over-constrain the search, retry with clean filters only.
    if (count($rows) === 0 && count($keywords) > 0) {
        $fallbackSql = "SELECT p.product_id, p.name, p.modal, p.description, p.price, p.cprice, p.quantity,
                               COALESCE(f.feature_blob, '') AS feature_blob,
                               COALESCE(b.name, '') AS brand_name, i.image_1
                        FROM tblproduct p
                        LEFT JOIN tblbrand b ON p.brand_id = b.brand_id AND b.status = 1
                        LEFT JOIN tblcategory c ON p.cat_id = c.cat_id
                        LEFT JOIN (
                            SELECT product_id, GROUP_CONCAT(CONCAT(feature_name, ': ', feature_value) ORDER BY feature_id SEPARATOR ' | ') AS feature_blob
                            FROM tblproduct_feature
                            GROUP BY product_id
                        ) f ON f.product_id = p.product_id
                        LEFT JOIN tblimage i ON p.product_id = i.product_id
                        WHERE p.status = 1 AND p.quantity > 0";
        $fallbackTypes = "";
        $fallbackParams = [];
        if ($budget !== null && $budget > 0) { $fallbackSql .= " AND p.price <= ?"; $fallbackTypes .= "d"; $fallbackParams[] = (float)$budget; }
        if ($brandMatch) { $fallbackSql .= " AND p.brand_id = ?"; $fallbackTypes .= "i"; $fallbackParams[] = (int)$brandMatch["brand_id"]; }
        if ($wantsPhonesOnly) $fallbackSql .= " AND (" . $phoneCategoryFilterSql . ")";
        $fallbackSql .= " ORDER BY p.price ASC LIMIT 48";
        $fallbackStmt = $conn->prepare($fallbackSql);
        if ($fallbackStmt) {
            if ($fallbackTypes !== "") {
                $fallbackBind = [$fallbackTypes];
                foreach ($fallbackParams as $k => $v) $fallbackBind[] = &$fallbackParams[$k];
                call_user_func_array([$fallbackStmt, "bind_param"], $fallbackBind);
            }
            $fallbackStmt->execute();
            $fallbackRes = $fallbackStmt->get_result();
            while ($fallbackRes && $row = $fallbackRes->fetch_assoc()) $rows[] = $row;
            $fallbackStmt->close();
        }
    }
    if (count($keywords) > 0 && count($rows) > 0) {
        usort($rows, function ($a, $b) use ($keywords) {
            $ca = keywordCoverageCount($a, $keywords);
            $cb = keywordCoverageCount($b, $keywords);
            if ($ca !== $cb) return $cb <=> $ca;
            $sa = scoreProductKeywordMatchRow($a, $keywords);
            $sb = scoreProductKeywordMatchRow($b, $keywords);
            if ($sa !== $sb) return $sb <=> $sa;
            return (float)$a["price"] <=> (float)$b["price"];
        });
    }
    $rows = narrowChatProductRowsToBestMatch($rows, $keywords, $message);
    $products = [];
    foreach ($rows as $row) {
        $descPlain = stripProductDescriptionForChat($row["description"] ?? "");
        $products[] = [
            "product_id" => (int)$row["product_id"],
            "name" => (string)$row["name"],
            "modal" => (string)($row["modal"] ?? ""),
            "description" => $descPlain,
            "feature_blob" => normalizeFeatureBlobForChat((string)($row["feature_blob"] ?? "")),
            "price" => (float)$row["price"],
            "cprice" => (float)($row["cprice"] ?? 0),
            "quantity" => (int)$row["quantity"],
            "brand_name" => (string)($row["brand_name"] ?? ""),
            "image" => (string)(($row["image_1"] ?? "") ?: "smartphone.png"),
            "product_url" => "product.php?product_id=" . (int)$row["product_id"],
        ];
    }
    return [$products, $keywords];
}

function detectBestPhonesWebIntent($message)
{
    $m = mb_strtolower((string)$message);
    $asksBest = (bool)preg_match('/\b(best|top|good|recommend|suggest)\b/u', $m);
    if (!$asksBest) return '';
    if (preg_match('/\b(gaming|game|fps|performance|chipset)\b/u', $m)) return 'gaming';
    if (preg_match('/\b(videography|video|cinematic|recording|stabilization|vlog)\b/u', $m)) return 'videography';
    if (preg_match('/\b(camera|photo|photography|selfie|portrait|night)\b/u', $m)) return 'camera';
    return '';
}

function detectBestValueIntent($message)
{
    $m = mb_strtolower((string)$message);
    return (bool)preg_match('/\b(value|money|affordable|budget|worth|price\s*to\s*performance|best buy)\b/u', $m);
}

function webGetText($url, $timeout = 12)
{
    $ch = curl_init((string)$url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
    curl_setopt($ch, CURLOPT_CONNECTTIMEOUT, 6);
    curl_setopt($ch, CURLOPT_TIMEOUT, (int)$timeout);
    curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
    curl_setopt($ch, CURLOPT_HTTPHEADER, [
        "User-Agent: R-TEL-Chat-Web/1.0",
        "Accept: text/html,application/xhtml+xml"
    ]);
    $body = curl_exec($ch);
    curl_close($ch);
    return is_string($body) ? $body : "";
}

function gsmCleanText($text)
{
    $t = html_entity_decode(strip_tags((string)$text), ENT_QUOTES | ENT_HTML5, "UTF-8");
    $t = preg_replace('/\s+/u', ' ', $t);
    return trim((string)$t);
}

function gsmFindCandidates($query, $limit = 3)
{
    $q = trim((string)$query);
    if ($q === '') return [];
    $html = webGetText("https://www.gsmarena.com/results.php3?sQuickSearch=yes&sName=" . rawurlencode($q), 12);
    if ($html === '') return [];
    $out = [];
    $seen = [];
    if (preg_match_all('/<a\s+href="([^"]+-\d+\.php)".*?<strong>(.*?)<\/strong>/is', $html, $m, PREG_SET_ORDER)) {
        foreach ($m as $row) {
            $name = gsmCleanText($row[2] ?? '');
            $href = trim((string)($row[1] ?? ''));
            if ($name === '' || $href === '') continue;
            $key = mb_strtolower($name);
            if (isset($seen[$key])) continue;
            $seen[$key] = true;
            $out[] = [
                'name' => $name,
                'url' => 'https://www.gsmarena.com/' . ltrim($href, '/')
            ];
            if (count($out) >= max(1, (int)$limit)) break;
        }
    }
    return $out;
}

function gsmParseSpecs($url)
{
    $html = webGetText((string)$url, 14);
    if ($html === '') return [];
    $pairs = [];
    if (preg_match_all('/<td[^>]*class="ttl"[^>]*>(.*?)<\/td>\s*<td[^>]*class="nfo"[^>]*>(.*?)<\/td>/is', $html, $m, PREG_SET_ORDER)) {
        foreach ($m as $row) {
            $k = mb_strtolower(gsmCleanText($row[1] ?? ''));
            $v = gsmCleanText($row[2] ?? '');
            if ($k === '' || $v === '') continue;
            if (!isset($pairs[$k])) $pairs[$k] = [];
            $pairs[$k][] = $v;
        }
    }
    $pick = function(array $keys) use ($pairs) {
        foreach ($keys as $k) {
            $kk = mb_strtolower((string)$k);
            if (!empty($pairs[$kk][0])) return trim((string)$pairs[$kk][0]);
        }
        return '';
    };
    return [
        'chipset' => $pick(['chipset']),
        'cpu' => $pick(['cpu']),
        'gpu' => $pick(['gpu']),
        'display' => $pick(['size']),
        'camera' => $pick(['triple', 'dual', 'quad', 'penta', 'single']),
        'battery' => $pick(['type']),
        'charging' => $pick(['charging']),
        'video' => $pick(['video']),
        'price' => $pick(['price'])
    ];
}

function parseApproxPriceFromSpecs(array $specs)
{
    $priceText = mb_strtolower(trim((string)($specs['price'] ?? '')));
    if ($priceText === '') return null;
    if (!preg_match('/(\d[\d,\.\s]{2,})/', $priceText, $m)) return null;
    $raw = preg_replace('/[^\d\.]/', '', (string)($m[1] ?? ''));
    if ($raw === '' || !is_numeric($raw)) return null;
    $value = (float)$raw;
    if ($value <= 0) return null;
    if (strpos($priceText, 'eur') !== false || strpos($priceText, '€') !== false) {
        return (int)round($value * 360.0);
    }
    if (strpos($priceText, 'usd') !== false || strpos($priceText, '$') !== false) {
        return (int)round($value * 320.0);
    }
    if (strpos($priceText, 'inr') !== false || strpos($priceText, '₹') !== false) {
        return (int)round($value * 3.8);
    }
    return (int)round($value);
}

function webRecommendationScore($intent, array $specs, $budget = null, $preferValue = false)
{
    $text = mb_strtolower(implode(' ', array_values($specs)));
    $score = 0.0;
    if ($intent === 'gaming') {
        if (preg_match('/snapdragon 8|dimensity 9|tensor g|a1[78]\s*pro|gen\s*[23]/', $text)) $score += 5;
        if (preg_match('/120hz|144hz|165hz/', $text)) $score += 2;
        if (preg_match('/5000\s*mah|5500\s*mah|6000\s*mah/', $text)) $score += 2;
        if (preg_match('/vc|cooling|gaming/', $text)) $score += 1;
    } elseif ($intent === 'camera') {
        if (preg_match('/200\s*mp|108\s*mp|50\s*mp/', $text)) $score += 3;
        if (preg_match('/ois|optical image stabilization/', $text)) $score += 2;
        if (preg_match('/ultrawide|telephoto|periscope/', $text)) $score += 2;
        if (preg_match('/hdr|night|portrait/', $text)) $score += 1;
    } elseif ($intent === 'videography') {
        if (preg_match('/8k|4k/', $text)) $score += 3;
        if (preg_match('/60fps|120fps/', $text)) $score += 2;
        if (preg_match('/gyro eis|ois|stabil/', $text)) $score += 3;
        if (preg_match('/dolby vision|hdr10/', $text)) $score += 1;
    }
    if ($budget !== null && (int)$budget > 0) {
        $approxLkr = parseApproxPriceFromSpecs($specs);
        if ($approxLkr !== null && $approxLkr > 0) {
            $b = (float)$budget;
            $ratio = abs($approxLkr - $b) / max($b, 1.0);
            if ($approxLkr <= $b) {
                $score += 3.5;
                if ($ratio <= 0.10) $score += 2.5;
                elseif ($ratio <= 0.20) $score += 1.25;
            } else {
                $score -= min(4.0, 1.5 + ($ratio * 2.5));
            }
        }
    }
    if ($preferValue) {
        $approxLkr = parseApproxPriceFromSpecs($specs);
        if ($approxLkr !== null && $approxLkr > 0) {
            // Encourage stronger specs at lower cost for "best value" requests.
            $score += max(0.0, min(4.0, 250000.0 / (float)$approxLkr));
            if ($budget !== null && (int)$budget > 0 && $approxLkr <= (int)$budget) $score += 1.5;
        }
    }
    return $score;
}

function buildBestPhonesWebReply($intent, $budget = null, $preferValue = false)
{
    $seedQueries = [
        'gaming' => ['Asus ROG Phone', 'Red Magic', 'Black Shark', 'iQOO', 'Poco F'],
        'camera' => ['iPhone Pro', 'Samsung Galaxy S Ultra', 'Google Pixel', 'Xiaomi Ultra', 'Vivo X'],
        'videography' => ['iPhone Pro Max', 'Samsung Galaxy S Ultra', 'Sony Xperia', 'Google Pixel', 'Vivo X']
    ];
    $topicLabel = $intent === 'gaming' ? 'gaming' : ($intent === 'camera' ? 'camera' : 'videography');
    $rows = [];
    $seen = [];
    foreach (($seedQueries[$intent] ?? []) as $q) {
        $cands = gsmFindCandidates($q, 2);
        foreach ($cands as $cand) {
            $name = trim((string)($cand['name'] ?? ''));
            $url = trim((string)($cand['url'] ?? ''));
            if ($name === '' || $url === '') continue;
            $key = mb_strtolower($name);
            if (isset($seen[$key])) continue;
            $seen[$key] = true;
            $specs = gsmParseSpecs($url);
            if (count(array_filter($specs)) === 0) continue;
            $rows[] = [
                'name' => $name,
                'url' => $url,
                'specs' => $specs,
                'score' => webRecommendationScore($intent, $specs, $budget, $preferValue)
            ];
            if (count($rows) >= 10) break 2;
        }
    }
    if (count($rows) === 0) {
        return "I could not load live web data right now for best {$topicLabel} phones. Please try again in a moment.";
    }
    usort($rows, function ($a, $b) {
        return (float)($b['score'] ?? 0) <=> (float)($a['score'] ?? 0);
    });
    $budgeted = [];
    if ($budget !== null && (int)$budget > 0) {
        foreach ($rows as $row) {
            $p = parseApproxPriceFromSpecs((array)($row['specs'] ?? []));
            if ($p !== null && $p <= (int)$budget) $budgeted[] = $row;
        }
    }
    $top = array_slice(count($budgeted) > 0 ? $budgeted : $rows, 0, 5);
    $lines = [];
    $header = "Best {$topicLabel} phones from live web specs (GSMArena)";
    if ($preferValue) $header = "Best value {$topicLabel} phones from live web specs (GSMArena)";
    if ($budget !== null && (int)$budget > 0) {
        $header .= " around/under Rs. " . number_format((float)$budget, 0);
    }
    $lines[] = $header . ":";
    foreach ($top as $idx => $row) {
        $s = $row['specs'];
        $bits = [];
        if (!empty($s['chipset'])) $bits[] = "Chipset: " . $s['chipset'];
        if (!empty($s['camera']) && $intent !== 'gaming') $bits[] = "Camera: " . $s['camera'];
        if (!empty($s['video']) && $intent === 'videography') $bits[] = "Video: " . $s['video'];
        if (!empty($s['battery'])) $bits[] = "Battery: " . $s['battery'];
        if (!empty($s['charging'])) $bits[] = "Charging: " . $s['charging'];
        $approx = parseApproxPriceFromSpecs($s);
        if ($approx !== null && $approx > 0) $bits[] = "Approx price: Rs. " . number_format((float)$approx, 0);
        $lines[] = "- " . ($idx + 1) . ") " . $row['name'] . (count($bits) ? " — " . implode(" | ", array_slice($bits, 0, 3)) : "");
    }
    $lines[] = "- Source: GSMArena web data.";
    return implode("\n", $lines);
}

function buildProductChatDraftReply(array $products, $scope)
{
    $n = count($products);
    if ($n === 0) return "No matching in-stock products on R-TEL for " . $scope . ". Try another model name, spelling, budget, or brand—or browse the shop.";
    if ($n === 1) {
        $p = $products[0];
        $lines = [];
        $lines[] = "On R-TEL this is listed as: " . $p["name"] . ($p["modal"] !== "" ? " (model: " . $p["modal"] . ")" : "") . ($p["brand_name"] !== "" ? ", brand: " . $p["brand_name"] : "") . ".";
        $lines[] = "Availability: in stock in our system (" . $p["quantity"] . " unit(s)). Price: Rs. " . number_format($p["price"], 2) . ".";
        if ((float)$p["cprice"] > 0 && (float)$p["cprice"] > (float)$p["price"]) $lines[] = "Compare price on site: Rs. " . number_format((float)$p["cprice"], 2) . ".";
        $descText = trim((string)($p["description"] ?? ""));
        $featureText = trim((string)($p["feature_blob"] ?? ""));
        if ($descText !== "" || $featureText !== "") {
            if ($descText !== "") {
                $snippet = mb_strlen($descText) > 1200 ? mb_substr($descText, 0, 1200) . "…" : $descText;
                $lines[] = "Features & details from our product page:\n" . $snippet;
            }
            if ($featureText !== "") {
                $lines[] = "Specifications from database:\n" . $featureText;
            }
        } else {
            $lines[] = "Specs are not filled in DB yet for this item. Open the product page for full details: " . $p["product_url"];
        }
        return implode("\n\n", $lines);
    }
    return "Found " . $n . " in-stock product(s) on R-TEL for " . $scope . ". Details for each item are on its product page; see the cards below.";
}

$data = json_decode(file_get_contents("php://input"), true);
$action = trim((string)($data["action"] ?? ""));
$rawMessage = trim((string)($data["message"] ?? ""));
$message = normalizeUserMessage($rawMessage);
ensureChatSessionTable($conn);
$userId = isset($_SESSION["user_id"]) ? (string)$_SESSION["user_id"] : "0";
$isPersistableUser = ($userId !== "" && $userId !== "0");

if ($action === "history") {
    if (!$isPersistableUser) {
        respond(["success" => true, "session_id" => "", "messages" => []]);
    }
    $history = getLatestChatHistory($conn, $userId);
    respond(["success" => true, "session_id" => $history["session_id"], "messages" => $history["messages"]]);
}
if ($message === "") respond(["success" => false, "reply" => "Please enter a message.", "products" => []]);

if (isClearHistoryCommand($message)) {
    if ($isPersistableUser) {
        $deleteStmt = $conn->prepare("DELETE FROM tblchat_session WHERE cus_id = ?");
        if ($deleteStmt) { $deleteStmt->bind_param("s", $userId); $deleteStmt->execute(); $deleteStmt->close(); }
    }
    respond(["success" => true, "reply" => "Your chat history has been erased successfully.", "products" => [], "session_id" => "", "history_cleared" => true]);
}

$incomingSessionId = trim((string)($data["session_id"] ?? ""));
$sessionId = "";
if ($isPersistableUser) {
    $sessionId = $incomingSessionId !== "" ? $incomingSessionId : createChatSession($conn, $userId, $message);
}
$allowedKeywords = getAllowedTopicKeywords();
$faqRules = getSystemFaqRules();
$messyInput = isLikelyMessyInput($rawMessage);
$messyIntent = $messyInput ? guessIntentFromMessyInput($message) : "unknown";

if (!isAllowedTopic($message, $allowedKeywords) && $messyIntent === "unknown") {
    $blockedReply = "I can only help with R-TEL shopping: products, prices, cart, checkout, orders, account, shipping, coupons, ratings, feedback, and site issues (bugs/errors). Please rephrase using those topics.";
    if ($isPersistableUser && $sessionId !== "") {
        appendToTranscript($conn, $sessionId, $message, $blockedReply);
    }
    respond(["success" => true, "reply" => $blockedReply, "products" => [], "session_id" => $sessionId]);
}

$products = [];
$reply = "";
$faqHint = null;
$skipAiPolish = false;
$replySource = "fallback";
$replyProvider = "";
$productIntent = isProductIntent($message) || $messyIntent === "product";
if ($productIntent) {
    $webBestIntent = detectBestPhonesWebIntent($message);
    if ($webBestIntent !== '') {
        $webBudget = extractBudget($message);
        $preferValue = detectBestValueIntent($message);
        $reply = buildBestPhonesWebReply($webBestIntent, $webBudget, $preferValue);
        $skipAiPolish = true;
    } else {
    $budget = extractBudget($message);
    $brandMatch = detectBrandFromMessage($conn, $message);
    list($products, $searchKeywords) = fetchProductsForChat($conn, $message, $budget, $brandMatch);
    $replyParts = [];
    if ($brandMatch) $replyParts[] = "brand: " . $brandMatch["brand_name"];
    if ($budget !== null && $budget > 0) $replyParts[] = "budget under Rs. " . number_format((float)$budget, 2);
    if (count($searchKeywords) > 0) $replyParts[] = "search: " . implode(" ", $searchKeywords);
    $scope = count($replyParts) > 0 ? implode(", ", $replyParts) : "your request";
    $reply = buildProductChatDraftReply($products, $scope);
    }
} else {
    $faqAnswer = resolveFaqAnswer($message, $faqRules);
    if ($faqAnswer !== null) {
        $faqHint = $faqAnswer; $reply = $faqAnswer;
    } elseif (isSupportIssueIntent($message) || $messyIntent === "support") {
        $reply = getDefaultSupportTroubleshootingDraft(); $faqHint = $reply;
    } else {
        $reply = "I can help with all R-TEL product questions (model names, specs, stock, prices), cart, checkout, orders, account, shipping, coupons, ratings, feedback, and troubleshooting site problems. What would you like to know?";
    }
}

if ($messyInput && $faqHint === null && count($products) === 0) {
    $reply = "I understood your message. Please send one short line in simple form, like: 'Samsung phone under 50000' or 'Checkout not working'. I will help quickly.";
}

if (!$skipAiPolish) {
    $reply = generateAssistantReplyWithRealAi($message, $reply, $products, $faqHint);
    $reply = simplifyEnglishReply($reply);
    if (function_exists('rtel_get_last_ai_reply_source')) {
        $replySource = (string)rtel_get_last_ai_reply_source();
    }
    if (function_exists('rtel_get_last_ai_provider')) {
        $replyProvider = (string)rtel_get_last_ai_provider();
    }
}
if ($isPersistableUser && $sessionId !== "") {
    appendToTranscript($conn, $sessionId, $message, $reply);
}
respond([
    "success" => true,
    "reply" => $reply,
    "products" => $products,
    "session_id" => $sessionId,
    "reply_source" => $replySource,
    "ai_provider" => $replyProvider
]);
